### PR TITLE
The proposal for the evolution process itself (MP-0001)

### PR DESCRIPTION
**Pull request by heiko-braun**

### CODE REVIEW

**Comment by heiko-braun** [comment]
@karianna This can be put on hold until we've had the conference call: https://groups.google.com/forum/#!topic/microprofile/yjFD_7jIE9Y

**Comment by karianna** [comment]
Shall we merge this now or do you want to update it?

**Comment by heiko-braun** [comment]
We agreed to first modify it to reflect the changes discussed on the call

**Comment by heiko-braun** [comment]
@karianna maybe we should merge it as "the first version" of the process and the submit additional PR's for changes as we discover them

**Comment by heiko-braun** [comment]
I've also updated to proposal number to `0000` to indicate that it's the root proposal. When others come in we need to have an eye on used/unused proposal numbers

**Comment by karianna** [comment]
Much like the JEP process in OpenJDK could we have a list of the proprosal numbers and names on the README.md file?

**Comment by heiko-braun** [comment]
Yes, i think it would be good to extract these and include them in the webpage. So people easily see what proposal are under review, being worked on, implemented, etc

**Pull request merged**
