### PR TITLE
MP-0002: Metrics/Telemetry

### PR DESCRIPTION
**Pull request by pilhuhn**
Signed-off-by: Heiko W. Rupp <hrupp@redhat.com>

# Proposal for a MicroProfile specification

**! DO NOT MERGE this Pull Request BEFORE REVIEW is finished!**

**Merging this Pull Request means that the proposal is officially accepted by the MicroProfile Core Team as a MicroProfile incubation project. A public discussion and an agreement within the MicroProfile Core Team is expected before a proposal is accepted/rejected.** 

_If this PR is not a proposal for a new specification, delete this template description._

## Suggested steps to follow before this proposal is accepted ##

 - add label `proposal` to this PR on github
 - initiate a public discussion on the mP mailing list
   - Email Subject: "Review announcement: <<PROPOSAL_NAME>>"
   - Email Body: Based on [review announcement template](https://github.com/microprofile/evolution/blob/master/process.md#review-announcement) 
       - fill in `<<PROPOSAL NAME>>`, `<<REVIEW END DATE>>` (not mandatory, can be announced later, but should be at least 7 days after the announcement email is sent) 
       and `<<REVIEW MANAGER NAME>>` (the name of the sender)
       - update the link to a proposal (NNNN-proposal.md) to point to this Pull Request

After the review, the Core Team should form an agreement whether or not to accept the proposal, or whether ask its author for amendments. 

Once this Pull Reuest is merged, the proposal is considered accepted and an incubation repository should be created to facilitate collaboration.

### CODE REVIEW

**Comment by mikecroft** [comment]
I think the IP validation is failing because you don't have Eclipse committer status, or perhaps because you haven't linked your GitHub profile to your Eclipse account. Wayne Beaton might be the best person to ask about it.

**Comment by mikecroft** [comment]
Also, I think some of your other commits have gone missing - I'm not sure how, but they seem to have ended up in the `eclipse/microprofile-evolution-process` repo, but not in any branch or tag:

https://github.com/eclipse/microprofile-evolution-process/commits/8eb917d64ed9b7ac670e959af39cbca5d8f6966b

Perhaps your local branch has it's upstream remote incorrectly set as the `eclipse` repository instead of your own `pilhuhn` repository?

**Comment by pilhuhn** [comment]
@mikecroft Yeah, I thought i had the profile updated correctly, but probably not.

Wrt the commits - I have done a rebase of the commits on each other and then a force push, which probably explains why they seem missing now. The commit attached to this PR looks complete to me.

**Comment by gadekarl** [comment]
@pilhuhn I think the spec should also address some of the major concerns that we ran into in the field i.e standardize a way to propagate circuit breaker pattern being fired. When the circuit breaker is tripped, the micro service api may be responsive and other health params may also be good but the business use case is not fully functional and customers want to know that so that they can take appropriate action. This is one of the major pain point we are experiencing in the field. There are many point solutions like Hystrix currently which propagate the information in non-standard way. To gather data from these solutions, monitoring tools need to implement custom solutions for each of the source and it's hard to keep track of them. Standardizing would have substantial customer benefit.

**Comment by kenfinnigan** [comment]
@pilhuhn can you update PR with your git commit signature and I will merge as part of process clean up?

Thanks

**Comment by pilhuhn** [comment]
Closing. Will submit a new one.

**Pull request closed without merging**
